'use strict';

module.exports = {
    KEY_MISSING: '400',
    INVALID_DOC_ID: '401',
    INVALID_DATE: '402',
    INVALID_COLLECTION: '403',
    INVALID_DOCTYPE: '404',
    INVALID_INVENTORY: '405',
    BAD_EVENT: '406',
    INVALID_CREDENTIALS: '407'
};
